# -*- coding: utf-8 -*-
"""Runlevel UGOS apps for Stats Hub — AUTO-GENERATED by tools/gen_stats_hub_registry.py."""
from __future__ import annotations

from typing import Any

RUNLEVEL_APPS: list[dict[str, Any]] = [
    {"id": 'com.runlevel.transferhub', "name": 'Transfer Hub', "port": 29100, "summary_path": '/api/profiles', "kind": 'profiles'},
    {"id": 'com.runlevel.backupverifier', "name": 'Backup Verifier', "port": 29110, "summary_path": '/api/jobs', "kind": 'jobs'},
    {"id": 'com.runlevel.wakesync', "name": 'Wake & Sync', "port": 29120, "summary_path": '/api/plans', "kind": 'plans'},
    {"id": 'com.runlevel.statshub', "name": 'Stats Hub', "port": 29125, "summary_path": '/api/snapshot', "kind": 'snapshot', "self": True},
    {"id": 'com.runlevel.securityhub', "name": 'Security Hub', "port": 29130, "summary_path": '/api/events', "kind": 'security'},
    {"id": 'com.runlevel.lockandkey', "name": 'Lock & Key', "port": 29135, "summary_path": '/api/vaults', "kind": 'vaults'},
    {"id": 'com.runlevel.icloudpull', "name": 'iCloud Pull', "port": 29140, "summary_path": '/api/status', "kind": 'icloud_sync'},
]
